# action 的名称
name: github

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 安装yarn
        run: yarn
      - name: 安装依赖
        run: yarn install
      - name: 打包
        run: yarn run build
      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: abstract-umi
