name: prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 安装node
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      - name: 安装yarn
        run: yarn
      - name: 安装依赖
        run: yarn install
      - name: 打包
        run: yarn run build
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "abstract-umi/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/prod/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
